- name: Remove Broker containers
  docker_container:
    name: "{{ item }}"
    state: absent
  with_items:
    - brokeri2m
    - brokeri2s 
    - brokere3m
    - brokere3s

- name: Wait 10 seconds before recreating broker
  pause:
    seconds: 10

- name: Start Broker Interior 2 Master
  docker_container:
    name: brokeri2m
    image: "{{ image_broker }}"
    recreate: yes
    state: started
    networks:
      - name: lab0
        ipv4_address: 192.168.8.10
        aliases:
          - brokeri2m
        links:
          - I2
    volumes:
      - "{{playbook_dir}}/configs/broker-interior/master:/opt/broker1/etc"

- name: Start Broker Interior 2 Slave
  docker_container:
    name: brokeri2s
    image: "{{ image_broker }}"
    recreate: yes
    state: started
    networks:
      - name: lab0
        ipv4_address: 192.168.8.20
        aliases:
          - brokeri2s
        links:
          - I2
          - brokeri2m
    volumes:
      - "{{playbook_dir}}/configs/broker-interior/slave:/opt/broker1/etc"

- name: Start Broker Edge 3 Master
  docker_container:
    name: brokere3m
    image: "{{ image_broker }}"
    recreate: yes
    state: started
    networks:
      - name: lab0
        ipv4_address: 192.168.8.30
        aliases:
          - brokere3m
        links:
          - E3
    volumes:
      - "{{playbook_dir}}/configs/broker-edge/master:/opt/broker1/etc"

- name: Start Broker Edge 3 Slave
  docker_container:
    name: brokere3s
    image: "{{ image_broker }}"
    recreate: yes
    state: started
    networks:
      - name: lab0
        ipv4_address: 192.168.8.40
        aliases:
          - brokere3s
        links:
          - E3
          - brokere3m
    volumes:
      - "{{playbook_dir}}/configs/broker-edge/slave:/opt/broker1/etc"

- name: Wait 30 seconds till Master and Slave handshake is complete
  pause:
    seconds: 30
