---
- name: "Creating configuration directories"
  file:
    path: "{{ role_path }}/files/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - Router.I1
    - Router.I2
    - Router.I3
    - Router.E1
    - Router.E2
    - Router.E3

- name: "Copying router configuration files"
  synchronize:
    src: "{{ role_path }}/files/{{ item }}/"
    dest: "{{ role_path }}/files/{{ item }}"
  with_items:
    - Router.I1
    - Router.I2
    - Router.I3
    - Router.E1
    - Router.E2
    - Router.E3

