---
# docker run --rm --cap-add NET_ADMIN --net=container:<container-to-delay> gaiadocker/iproute2 qdisc add dev eth0 root netem delay 3000ms
- name: Delay victim container
  docker_container:
    name: delay
    image: "gaiadocker/iproute2"
    state: started
    auto_remove: yes
    network_mode: "container:{{ delay_victim }}"
    capabilities: 
      - NET_ADMIN
    command: "qdisc add dev eth1 root netem delay {{ delay_time }}"
  ignore_errors: true

