---
- name: Wait 10 seconds before creating edge routers
  pause:
    seconds: 10

- name: Start Edge Router.E1
  docker_container:
    name: Router.E1
    image: "{{ image_router }}"
    command: "qdrouterd -c /var/lib/qdrouterd/qdrouterd.conf"
    state: started
    recreate: yes
    published_ports: 7001:7001
    networks:
      - name: lab0
        aliases:
          - E1
        links:
          - I1
    volumes:
      - "{{ role_path }}/files/Router.E1:/var/lib/qdrouterd:Z"

- name: Start Edge Router.E2
  docker_container:
    name: Router.E2
    image: "{{ image_router }}"
    command: "qdrouterd -c /var/lib/qdrouterd/qdrouterd.conf"
    state: started
    recreate: yes
    published_ports: 7002:7002
    networks:
      - name: lab0
        aliases:
          - E2
        links:
          - I2
    volumes:
      - "{{ role_path }}/files/Router.E2:/var/lib/qdrouterd:Z"

- name: Start Edge Router.E3
  docker_container:
    name: Router.E3
    image: "{{ image_router }}"
    command: "qdrouterd -c /var/lib/qdrouterd/qdrouterd.conf"
    state: started
    published_ports: 7003:7003
    recreate: yes
    networks:
      - name: lab0
        aliases:
          - E3
        links:
          - I3
          - brokere3m
          - brokere3s
    volumes:
      - "{{ role_path }}/files/Router.E3:/var/lib/qdrouterd:Z"
