- name: Allow access to TCP ports with iptables
  shell: "iptables -I INPUT -p tcp --dport {{ item }} -j ACCEPT"
  with_items:
    - "2375"
    - "5656:5678"
    - "6001:6003"
    - "7001:7003"
    - "8161:8162"
    - "61616"
  when: ansible_distribution_major_version|int < 8

# Could not use firewalld module with python3 (missing python3-firewall package)
- name: Allow access to TCP ports with firewalld-cmd
  command: "firewall-cmd --zone=public --add-port={{ item }}/tcp --permanent"
  when: ansible_distribution_major_version|int >= 7
  ignore_errors: true
  with_items:
    - "2375"
    - "5656-5678"
    - "6001-6003"
    - "7001-7003"
    - "8161-8162"
    - "61616"

- name: Reloading firewalld rules
  command: "firewall-cmd --reload"
  when: ansible_distribution_major_version|int >= 7
  ignore_errors: true

