---
#
# Ensures that environment is not prepared for deploying to VMs through SSH
# as we are using a unique inventory file, setting up the environment variables
# can cause problems or unexpected behavior
#
- hosts: localhost
  tasks:
    - name: Assert environment variables are not set for each router host
      assert:
        that: lookup('env', item) == ''
        msg: "{{ item }} environment variable cannot be set"
      with_items: [Router_I1, Router_I2, Router_I3, Router_E1, Router_E2, Router_E3]

# Undeploy previus topology if exist
- hosts: docker-host
  tasks:
    # PYTHON3SCL - When using python3 from RHSCL the selinux module is failing
    #              as it expects an /usr/bin/python3 executable to exist
    #              A PR has been submitted to the selinux pip module to fix
    #              this issue.
    - name: Creating link for python ansible_python_interpreter in /usr/bin
      command: "ln -s {{ ansible_python_interpreter }} /usr/bin/"
      ignore_errors: yes
    # END PYTHON3SCL
    - name: Installing pip modules
      pip:
        executable: "{{ pip_binary }}"
        name:
          - docker
          - selinux
    - name: Create lab0 network
      docker_network:
        name: lab0
        force: yes
        ipam_options:
          subnet: '192.168.8.0/24'

# Deploy the brokers
- hosts: docker-host
  roles:
    - role: brokers
      vars:
        deploy_interior: True
        deploy_edge: True
    - role: routers
      vars:
        deploy_to_containers: True
    - role: clients
