- hosts: localhost
  tasks:
    - include: ../../common/stop_client_containers.yml

- hosts: localhost
  vars:
    openshift_template_name: "amq-interconnect-1-sasldb-auth"
    role_action: "delete"
    sasldb: true
  roles:
    - ansible-interconnect-image
